Controllers/StudentController.cs
using CompleteApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CompleteApp.Controllers
{
    public class StudentController : Controller
    {
        StudentContext db = new StudentContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Getdata()
        {
            var students = db.Students.ToList();
            return Json(new { data = students }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Student());
            else
            {
                return View(db.Students.Where(x => x.StudentId == id).FirstOrDefault<Student>());
            }
        }

       

        [HttpPost]
        public ActionResult AddorEdit(Student student)
        {
            if(student.StudentId==0)
            {
                db.Entry(student).State = EntityState.Added;
                db.SaveChanges();
                return Json( new { success=true, message= "Saved Successfully done"}, JsonRequestBehavior.AllowGet);
            }
            else
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true, message = "Updated Successfully done" });
            }
          
        }

        public ActionResult Details(int id)
        {
            return View(db.Students.Where(c => c.StudentId == id).FirstOrDefault());
        }
      /*  public ActionResult Delete(int id)
        {
            var students = db.Students.Where(c => c.StudentId == id).FirstOrDefault();
            return View(students);
        }*/

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var students = db.Students.Where(c => c.StudentId == id).FirstOrDefault();
            db.Entry(students).State = EntityState.Deleted;
            db.SaveChanges();
           
            return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(int id)
        {
            return View(db.Students.Where(c => c.StudentId == id).FirstOrDefault());
        }

        [HttpPost]
        public ActionResult Edit(Student students)
        {
            db.Entry(students).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/UserController.cs
using CompleteApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CompleteApp.Controllers
{
    public class UserController : Controller
    {
        StudentContext _context= new StudentContext();
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult List()
        {
            return Json(_context.Users.ToList(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Add(Users user)
        {
            _context.Users.Add(user);
            _context.SaveChanges();
            return Json(new { success = true, message = "Added Successfully" }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetbyID(int ID)
        {
            return Json(_context.Users.FirstOrDefault(x => x.Id == ID), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Update(Users user)
        {
            var data = _context.Users.FirstOrDefault(x => x.Id == user.Id);
            if (data != null)
            {
                data.Name = user.Name;
                data.State = user.State;
                data.Country = user.Country;
                data.Age = user.Age;
                _context.SaveChanges();
            }
            return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Delete(int ID)
        {

           
            var data = _context.Users.FirstOrDefault(x => x.Id == ID);
            _context.Users.Remove(data);
            _context.SaveChanges();
            return Json( new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

 
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("User List", "Index", "User")</li>
                    <li>@Html.ActionLink("Employee", "Index", "Employee")</li>
                    <li>@Html.ActionLink("Student List", "Index", "Student")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    <script src="~/Scripts/User.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/Scripts/notify.min.js"></script>
</body>
</html>